name: Secure Deploy A.A Fashion

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to manualy trigger a scan/deploy if needed

# Principle of Least Privilege: Grant only what is needed for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment to prevent race conditions
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Security Scan (Checkov)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: all
          soft_fail: true # Allows us to see security reports without stopping the brand launch

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This uploads the entire root directory (index.html, css, images)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4